### ISSUE TITLE
Entry point for non-linguists

### ISSUE THREAD

**Issue by jumasheff** [apertium/apertium-kir#11]
Hey @jonorthwash @ftyers !

Today I showed this repo to a person who is trying to build an app for Kyrgyz language learners.
He is going to use Udahin's ky-ru, ru-ky dictionaries (you can view [files here](https://drive.google.com/file/d/0B4kQrluFTjLmWFN3MnBOZnZ4UTQ/view?usp=sharing&resourcekey=0-vljhKNglbK-W8aRPa9FMcQ)) and asked me to help him with POS tagging. I showed the README examples and also mentioned Apertium's UD building efforts. I told him that the best thing to do is to start helping Apertium with UD and learn how a proper tagging should look like.
But I don't think a person without special training will be happy to see and use Apertium/UD tags.

Questions: 

1. Are there low-hanging fruits in this project?
2. How can a regular person contribute to this project?
3. Are there online courses that teach things related to UD? 🙏 

I think that Apertium is a fundamental tool that paves a path for Kyrgyz language to the world of computational linguistics and eventually AI (in its broad sense).
I'd even teach a course on CompLing using Apertium at our local universities (only after getting educated myself, of course).

**Comment by jumasheff** [comment]
UPD:
Found this crash course on Linguistics: https://youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW
I don't expect that it'll help me to understand Apertium better, though. Just an intro stuff.

**Comment by jonorthwash** [comment]
@jumasheff, somehow I missed this!

@IlnarSelimcan put together a guide for Kazakh speakers to expand `apertium-kaz`.  I believe part of it is [here](https://apertium.github.io/apertium-kaz/), but I remember there being more.

Since needs change in terms of where to focus attention within a given transducer, it's a little hard to put together a good guide.  I'd be very happy to talk (or work) with someone on anything related to Kyrgyz transducer or UD, though!

**Comment by jumasheff** [comment]
@jonorthwash Hey, thank you!

I am going to create a products NER for Kyrgyz and I think it's a good chance to learn everything related to CoNLL-U.
I'll get back to you later with actual sentences :)
